version: '3.2'

services:
  postgres:
    container_name: postgres-tactics-wiki
    image: postgres:latest
    restart: unless-stopped
    networks:
      - tactics-wiki
    ports:
      - '5432:5432'
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Pass@123456
      POSTGRES_USER: tactics-wiki
      POSTGRES_DB: tactics-wiki

  redis:
    container_name: redis-tactics-wiki
    image: bitnami/redis:latest
    restart: unless-stopped
    networks:
      - tactics-wiki
    ports:
      - '6379:6379'
    volumes:
      - ./db/redis:/bitnami/redis/data
    environment:
      # REDIS_PASSWORD: Pass@123456
      ALLOW_EMPTY_PASSWORD: yes

networks:
  tactics-wiki:
    driver: bridge
